global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
  - job_name: "otel-collector-telemetry"
    static_configs:
      - targets: ["otel-collector:8888"]

remote_write:
  - url: "http://victoriametrics:8428/api/v1/write"